name: pyvista-doc-auto-update
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  script:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Checkout with submodule
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        repository: pyvista/pyvista-doc-translations
        submodules: true
        path: pyvista-doc-translations
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3-setuptools
        sudo apt-get install -y --no-install-recommends libgl1-mesa-dev xvfb ffmpeg
        sudo apt-get install -y --no-install-recommends python3-venv
        sudo apt-get install -y --no-install-recommends libgl1-mesa-glx
        sudo apt-get install -y --no-install-recommends python3-tk pandoc
        pip install -U pip setuptools wheel
        cd pyvista-doc-translations
        pip install -r ./requirements.txt
        cd ../
    - name: Build project
      env:
        DISPLAY: :99.0
        PYVISTA_OFF_SCREEN: True
      run: |
        cd pyvista-doc-translations
        set -x
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        set +x
        git submodule update --remote
        cd pyvista
        cd doc
        make phtml DEFAULTS="" SPHINXOPTS="-D language=ja -D locale_dirs='../../../locale'"
        cd ../../..
    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npm install -g netlify-cli
        netlify deploy --prod --dir=pyvista-doc-translations/pyvista/doc/_build/html
